nome = "Decio Caetano de Souza"

print(nome[0]) # Imprime o primeiro caractere da string, que é "G". O índice 0 corresponde ao primeiro caractere, o índice 1 corresponde ao segundo caractere, e assim por diante. O índice -1 corresponde ao último caractere, o índice -2 corresponde ao penúltimo caractere, e assim por diante.
print(nome[1]) # Imprime o segundo caractere da string, que é "u
print(nome[-2]) # Imprime o penúltimo caractere da string, que é "l". O índice -1 corresponde ao último caractere, o índice -2 corresponde ao penúltimo caractere, e assim por diante.
print(nome[0:9]) # Imprime os caracteres da string do índice 0 ao
print(nome[:9]) # Imprime os caracteres da string do início até o índice 9 (exclusivo), ou seja, os caracteres do índice 0 ao índice 8. O índice 0 corresponde ao primeiro caractere, o índice 1 corresponde ao segundo caractere, e assim por diante. O índice -1 corresponde ao último caractere, o índice -2 corresponde ao penúltimo caractere, e assim por diante.
print(nome[10:]) # Imprime os caracteres da string do índice 10 até o final da string. O índice 0 corresponde ao primeiro caractere, o índice 1 corresponde ao segundo caractere, e assim por diante. O índice -1 corresponde ao último caractere, o índice -2 corresponde ao penúltimo caractere, e assim por diante.
print(nome[10:16]) # Imprime os caracteres da string do índice 10 ao índice 15 (exclusivo), ou seja, os caracteres do índice 10 ao índice 15. O índice 0 corresponde ao primeiro caractere, o índice 1 corresponde ao segundo caractere, e assim por diante. O índice -1 corresponde ao último caractere, o índice -2 corresponde ao penúltimo caractere, e assim por diante.
print(nome[10:16:2]) # Imprime os caracteres da string do índice 10 ao índice 15 (exclusivo), pulando de 2 em 2 caracteres, ou seja, os caracteres do índice 10, índice 12 e índice 14. O índice 0 corresponde ao primeiro caractere, o índice 1 corresponde ao segundo caractere, e assim por diante. O índice -1 corresponde ao último caractere, o índice -2 corresponde ao penúltimo caractere, e assim por diante.
print(nome[:]) # Imprime todos os caracteres da string, do início ao fim. O índice 0 corresponde ao primeiro caractere, o índice 1 corresponde ao segundo caractere, e assim por diante. O índice -1 corresponde ao último caractere, o índice -2 corresponde ao penúltimo caractere, e assim por diante.
print(nome[::-1]) # Imprime todos os caracteres da string, do fim ao início, ou seja, a string invertida. O índice 0 corresponde ao primeiro caractere, o índice 1 corresponde ao segundo caractere, e assim por diante. O índice -1 corresponde ao último caractere, o índice -2 corresponde ao penúltimo caractere, e assim por diante. O passo -1 indica que a string deve ser percorrida de trás para frente.

PI = 3.14159
print(f"O valor de PI é {PI:.2f}") # O f antes da string indica que ela é uma f-string, ou seja, uma string formatada. Dentro da string, os marcadores de posição são indicados por chaves {}, e o conteúdo dentro das chaves é avaliado como uma expressão Python. O valor da expressão é convertido para string e inserido no lugar do marcador de posição. No exemplo acima, o marcador de posição {PI:.2f} é substituído pelo valor da variável PI formatado com duas casas decimais. O .2f indica que o número deve ser formatado como um número de ponto flutuante com duas casas decimais. Portanto, a saída será "O valor de PI é 3.14". É possível usar qualquer expressão Python dentro das chaves, incluindo operações matemáticas, chamadas de função, etc. 
# "Valor de PI é 3.14" é a string resultante da formatação, onde o valor de PI foi inserido no lugar do marcador de posição {PI:.2f} e formatado com duas casas decimais.

print(f"O valor de PI é {PI:10.2f}") # O f antes da string indica que ela é uma f-string, ou seja, uma string formatada. Dentro da string, os marcadores de posição são indicados por chaves {}, e o conteúdo dentro das chaves é avaliado como uma expressão Python. O valor da expressão é convertido para string e inserido no lugar do marcador de posição. No exemplo acima, o marcador de posição {PI:10.2f} é substituído pelo valor da variável PI formatado com uma largura mínima de 10 caracteres e duas casas decimais. O 10.2f indica que o número deve ser formatado como um número de ponto flutuante com duas casas decimais e preenchido com espaços em branco à esquerda para atingir a largura mínima de 10 caracteres. 
# "O valor de PI é  3.14" é a string resultante da formatação, onde o valor de PI foi inserido no lugar do marcador de posição {PI:10.2f} e formatado com uma largura mínima de 10 caracteres e duas casas decimais.
