# Old Style String Formatting
# Interpolar variáveis em strings, usando o sinal % ou o método format() ou f-strings (a partir do Python 3.6). 
# A interpolação de strings é uma forma de inserir valores de variáveis dentro de uma string, usando um formato específico.

nome = "Guilherme" 
idade = 28
profissao = "Progamador"
linguagem = "Python"
saldo = 45.435

dados = {"nome": "Guilherme", "idade": 28} # O dicionário é uma estrutura de dados que armazena pares de chave-valor. Ele é usado para representar dados de forma organizada e acessível. No exemplo acima, o dicionário dados tem as chaves "nome" e "idade", com os valores "Guilherme" e 28, respectivamente. O dicionário pode ser usado para passar os valores das variáveis como argumentos nomeados para o método format(), usando o operador de desempacotamento de dicionários (**).

print("Nome: %s Idade: %d" % (nome, idade)) # O %s é um marcador de posição para uma string, o %d é um marcador de posição para um número inteiro, o %f é um marcador de posição para um número de ponto flutuante. O %s pode ser usado para qualquer tipo de dado, pois ele converte o valor para string. O %d só pode ser usado para números inteiros, e o %f só pode ser usado para números de ponto flutuante. O número após o % indica a largura mínima do campo, e o número após o . indica a precisão do número de ponto flutuante.

print("Nome: {} Idade: {}".format(nome, idade)) # O {} é um marcador de posição para uma string, um número inteiro ou um número de ponto flutuante. O método format() substitui os marcadores de posição pelos valores das variáveis passadas como argumentos, na ordem em que aparecem. Também é possível usar índices para especificar a ordem dos argumentos, ou usar nomes para especificar quais argumentos correspondem a quais marcadores de posição.

print("Nome: {1} Idade: {0}".format(idade, nome)) # O número dentro das chaves indica o índice do argumento passado para o método format(). O índice começa em 0, ou seja, o primeiro argumento tem índice 0, o segundo argumento tem índice 1, e assim por diante. No exemplo acima, o marcador de posição {1} corresponde ao segundo argumento (nome), e o marcador de posição {0} corresponde ao primeiro argumento (idade). Portanto, a saída será "Nome: Guilherme Idade: 28". É possível usar o mesmo índice várias vezes para repetir o mesmo valor em diferentes partes da string.
print("Nome: {1} Idade: {0} Nome: {1} {1}".format(idade, nome)) # O número dentro das chaves indica o índice do argumento passado para o método format(). O índice começa em 0, ou seja, o primeiro argumento tem índice 0, o segundo argumento tem índice 1, e assim por diante. No exemplo acima, o marcador de posição {1} corresponde ao segundo argumento (nome), e o marcador de posição {0} corresponde ao primeiro argumento (idade). Portanto, a saída será "Nome: Guilherme Idade: 28 Nome: Guilherme Guilherme". É possível usar o mesmo índice várias vezes para repetir o mesmo valor em diferentes partes da string.

print("Nome: {nome} Idade: {idade}".format(nome=nome, idade=idade)) # O nome dentro das chaves indica o nome do argumento passado para o método format(). O método format() substitui os marcadores de posição pelos valores dos argumentos correspondentes, usando os nomes para identificar quais argumentos correspondem a quais marcadores de posição. No exemplo acima, o marcador de posição {nome} corresponde ao argumento nome, e o marcador de posição {idade} corresponde ao argumento idade. Portanto, a saída será "Nome: Guilherme Idade: 28". É possível usar o mesmo nome várias vezes para repetir o mesmo valor em diferentes partes da string.
print("Nome: {name} Idade: {age} {name} {name} {age}".format(age=idade, name=nome)) # O nome dentro das chaves indica o nome do argumento passado para o método format(). O método format() substitui os marcadores de posição pelos valores dos argumentos correspondentes, usando os nomes para identificar quais argumentos correspondem a quais marcadores de posição. No exemplo acima, o marcador de posição {name} corresponde ao argumento name, e o marcador de posição {age} corresponde ao argumento age. Portanto, a saída será "Nome: Guilherme Idade: 28 Guilherme Guilherme 28". É possível usar o mesmo nome várias vezes para repetir o mesmo valor em diferentes partes da string.
print("Nome: {nome} Idade: {idade}".format(**dados)) # O ** é um operador de desempacotamento de dicionários, que permite passar os itens de um dicionário como argumentos nomeados para uma função. No exemplo acima, o dicionário dados tem as chaves "nome" e "idade", com os valores "Guilherme" e 28, respectivamente. O método format() substitui os marcadores de posição {nome} e {idade} pelos valores correspondentes do dicionário, usando as chaves para identificar quais valores correspondem a quais marcadores de posição. Portanto, a saída será "Nome: Guilherme Idade: 28". É possível usar o mesmo nome várias vezes para repetir o mesmo valor em diferentes partes da string.

print(f"Nome: {nome} Idade: {idade}") # O f antes da string indica que ela é uma f-string, ou seja, uma string formatada. Dentro da string, os marcadores de posição são indicados por chaves {}, e o conteúdo dentro das chaves é avaliado como uma expressão Python. O valor da expressão é convertido para string e inserido no lugar do marcador de posição. No exemplo acima, o marcador de posição {nome} é substituído pelo valor da variável nome, e o marcador de posição {idade} é substituído pelo valor da variável idade. Portanto, a saída será "Nome: Guilherme Idade: 28". É possível usar qualquer expressão Python dentro das chaves, incluindo operações matemáticas, chamadas de função, etc.
print(f"Nome: {nome} Idade: {idade} Saldo: {saldo:.2f}") # O f antes da string indica que ela é uma f-string, ou seja, uma string formatada. Dentro da string, os marcadores de posição são indicados por chaves {}, e o conteúdo dentro das chaves é avaliado como uma expressão Python. O valor da expressão é convertido para string e inserido no lugar do marcador de posição. No exemplo acima, o marcador de posição {nome} é substituído pelo valor da variável nome, o marcador de posição {idade} é substituído pelo valor da variável idade, e o marcador de posição {saldo:.2f} é substituído pelo valor da variável saldo formatado com duas casas decimais. O .2f indica que o número deve ser formatado como um número de ponto flutuante com duas casas decimais. Portanto, a saída será "Nome: Guilherme Idade: 28 Saldo: 45.44". É possível usar qualquer expressão Python dentro das chaves, incluindo operações matemáticas, chamadas de função, etc.
print(f"Nome: {nome} Idade: {idade} Saldo: {saldo:10.1f}") # O f antes da string indica que ela é uma f-string, ou seja, uma string formatada. Dentro da string, os marcadores de posição são indicados por chaves {}, e o conteúdo dentro das chaves é avaliado como uma expressão Python. O valor da expressão é convertido para string e inserido no lugar do marcador de posição. No exemplo acima, o marcador de posição {nome} é substituído pelo valor da variável nome, o marcador de posição {idade} é substituído pelo valor da variável idade, e o marcador de posição {saldo:10.1f} é substituído pelo valor da variável saldo formatado com uma largura mínima de 10 caracteres e uma casa decimal. O 10.1f indica que o número deve ser formatado como um número de ponto flutuante com uma casa decimal e preenchido com espaços em branco à esquerda para atingir a largura mínima de 10 caracteres. Portanto, a saída será "Nome: Guilherme Idade: 28 Saldo:       45.4". É possível usar qualquer expressão Python dentro das chaves, incluindo operações matemáticas, chamadas de função, etc.
